export type {
  AnnotationPayload,
  AnnotationType,
  AuthHandoffCookie,
  AuthHandoffRequest,
  AuthHandoffResult,
  BrowserSession,
  BrowserSessionStatus,
  BrowserTab,
  BrowserTabStatus,
  ScreenshotFrame,
  ScreenshotStreamConfig,
  SteerAction,
  TabEvent,
  TabEventType,
  TraceMetadata,
} from "./session.js"
